export const CALL_LIST_DATA = "CALL_LIST_DATA";
export const CALL_LIST_DATA_SUCCESS = "CALL_LIST_DATA_SUCCESS";
export const CALL_LIST_DATA_FALSE = "CALL_LIST_DATA_FALSE";
export const DELETE_TODO = "DELETE_TODO";
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS";
